export const MESSAGES = {
  SAVE_CONTENT: "SAVE_CONTENT",
  GET_PICTURE_URLS: "GET_PICTURE_URLS",
  RECEIVE_IMAGES_URLS: "RECEIVE_IMAGES_URLS",
  IMAGES_GALLERY_COMPLETED: "IMAGES_GALLERY_COMPLETED",
  SAVE_ALL_CONTENT: "SAVE_ALL_CONTENT",
  GET_IMAGE_URL_FOR_GALLERY: "GET_IMAGE_URL_FOR_GALLERY",
  RECEIVE_ORIGINAL_URL: "RECEIVE_ORIGINAL_URL",
  RECEIVE_ORIGINAL_IMAGE_URL: "RECEIVE_ORIGINAL_IMAGE_URL",
  RECEIVE_DOWNLOADING_PROGRESS: "RECEIVE_DOWNLOADING_PROGRESS",
  STOP_DOWNLOADING: "STOP_DOWNLOADING",
  GET_ALL_IMAGES_URLS_FOR_GALLERY: "GET_ALL_IMAGES_URLS_FOR_GALLERY",
  RECEIVE_PRELOADED_IMAGES_URLS: "RECEIVE_PRELOADED_IMAGES_URLS",
  OPEN_SETTINGS: "OPEN_SETTINGS",
};

export const EXTRACTION_REASON = {
  DOWNLOAD: "DOWNLOAD",
  NO_THUMB: "NO_THUMB",
  FOR_GALLERY: "FOR_GALLERY",
}

export const MAX_FILE_NAME = 100;

export const SCRIPTS = {
  PAGE: "/page-script.js",
  EXTRACT_ALL_IMAGES_URLS: "/extract-all-images-urls.js",
  DOWNLOAD_ORIGINAL_IMAGE_URL: "/download-original-special-case.js",
};

export const IMAGES_GALLERY_URL = "/images-gallery/index.html";

export const ERRORS = {
  INVALID_URL: "Invalid URL",
};
